@startuml
[*] -> 休眠状态 : 初始状态

休眠状态 -> 正常工作 : 早上7点自动启动
正常工作 -> 检测水量 : 启动后检测温度

检测水量 -> 烧水 : 温度低于20°且水箱有水
检测水量 ---> 不烧水 : 温度低于20°且水箱无水
检测水量 -> [*] : 温度在20°~100°之间，保持状态

烧水 -> 检测温度 : 开始烧水
烧水 -> 维修状态 : 水箱烧坏

检测温度 -> 断开电源 : 温度达到100°
断开电源 --> 检测水量 : 断开电源，重新检测水量

休眠状态 -> 断开电源 : 晚上11点自动断开电源

@enduml
