@startuml
[*] --> 等待输入 : 初始状态

等待输入 -> 读取字符 : 户主开始输入密码
读取字符 --> 验证密码 : 输入达到4位
验证密码 --> 系统功能选择 : 密码正确
验证密码 --> 锁定状态 : 密码错误3次

锁定状态 -down-> 等待输入 : 锁定时间超过120秒，重新允许输入

读取字符 --> 读取字符 : 每次输入一个字符
系统功能选择 --> [*] : 退出系统

@enduml
