@startuml

' 用例图
left to right direction
actor 用户
actor 系统管理员
actor 护士
actor 第三方支付系统
actor 医院挂号处工作人员

用户 --> (查看医院信息)
用户 --> (使用身份证注册)
用户 --> (使用手机号/验证码登录)
用户 --> (使用微信公众号登录)
用户 --> (绑定手机号)
用户 --> (预约挂号)
用户 --> (取消预约)
用户 --> (打印预约单)
用户 --> (打印挂号单)
用户 --> (在线支付费用)
用户 --> (就诊)
用户 --> (接收通知)
用户 --> (代患者挂号)

系统管理员 --> (审核用户注册)
系统管理员 --> (维护医生出诊信息)
系统管理员 --> (设置通知规则)
系统管理员 --> (设定用户初始信用等级)

护士 --> (核查预约单)
护士 --> (盖章确认预约)

第三方支付系统 --> (处理支付)

医院挂号处工作人员 --> (核查预约单)
医院挂号处工作人员 --> (打印挂号单)
医院挂号处工作人员 --> (盖章确认挂号)
医院挂号处工作人员 --> (当天取消预约)

@enduml