@startuml
actor 用户
entity 医院信息界面
entity 预约界面
control 预约挂号控制器
entity 医生
entity 预约单

用户 -[hidden]-> 医院信息界面
用户 -[hidden]-> 预约界面
用户 -[hidden]-> 预约挂号控制器
用户 -[hidden]-> 医生
用户 -[hidden]-> 预约单
医院信息界面 -> 用户 : 返回医院信息
预约界面 -> 用户 : 返回预约信息
预约挂号控制器 -> 医生 : 查询可预约医生
预约挂号控制器 -> 预约单 : 创建预约单
预约挂号控制器 -> 用户 : 返回预约单
@enduml
