@startuml
'https://plantuml.com/sequence-diagram

class Thoroughbred {
    - mother : Thoroughbred
    - father : Thoroughbred
    - birthYear : int
    - getCurrentAge() : int
    - getMother() : Thoroughbred
    - getFather() : Thoroughbred
}

@enduml